<?xml version="1.0" encoding="utf-8"?>

<!--
  Copyright (c) 1999-2004 DataPower Technology, Inc.
  All Rights Reserved.
-->
<!--
  Licensed Materials - Property of IBM
  IBM WebSphere DataPower Appliances
  Copyright IBM Corporation 2007,2008. All Rights Reserved.
  US Government Users Restricted Rights - Use, duplication or disclosure
  restricted by GSA ADP Schedule Contract with IBM Corp.
-->

<definitions name="mgmt-interface"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soapbind="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:wsdlsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
  xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/"
  xmlns:dp="http://www.datapower.com/schemas/management"
  xmlns:dpw="http://www.datapower.com/schemas/management/wsdl"
  targetNamespace="http://www.datapower.com/schemas/management/wsdl">

  <types>
    <xsd:schema
      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
      targetNamespace="http://www.datapower.com/schemas/management/wsdl">
      <xsd:import
        namespace="http://www.datapower.com/schemas/management"
        schemaLocation="xml-mgmt-2004.xsd"/>
    </xsd:schema>
  </types>

  <message name="mgmt-request">
    <part name="body" element="dp:request"/>
  </message>

  <message name="mgmt-response">
    <part name="body" element="dp:response"/>
  </message>

  <portType name="mgmt-port-type">
    <operation name="mgmt-operation">
      <input name="mgmt-operation-request" message="dpw:mgmt-request"/>
      <output name="mgmt-operation-response" message="dpw:mgmt-response"/>
    </operation>
  </portType>

  <binding name="mgmt-binding" type="dpw:mgmt-port-type">
    <soapbind:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="mgmt-operation">
      <soapbind:operation style="document"/>
      <input name="mgmt-operation-request">
        <soapbind:body use="literal"/>
      </input>
      <output name="mgmt-operation-response">
        <soapbind:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="mgmt-interface">
    <port name="mgmt-port" binding="dpw:mgmt-binding">
      <documentation>
        <wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.0"></wsi:Claim>
      </documentation>
      <!-- The location host address must be specified -->
      <soapbind:address location="https://localhost/service/mgmt/2004"/>
    </port>
  </service>

  <!-- SOAP 1.2 bindings are generated by xmlmgmt-produce-wsdl.xsl -->

</definitions>
